### ISSUE TITLE
Google map embeding doesn't work

### ISSUE THREAD

**Issue by neorganic** [luminousrubyist/airspace-jekyll#1]
Google map doesn't works on your demo. 

I managed to get it running when testing on localhost when it's without baseurl, but when i have baseurl it doesn't work and I can't found where is the problem. Hope you have all the answers.

**Comment by luminousrubyist** [comment]
Hi!

The Google Map embed is written using mysterious ThemeFisher Javascript that creates a custom map with ThemeFisher settings. Embedding this proprietary map requires API keys, so the most likely failure is Google Maps not loading as a result of the missing keys.

I've been meaning to change this code over for awhile to a version that doesn't require API keys. I've taken the liberty of making this change in my [latest commit](https://github.com/luminousrubyist/airspace-jekyll/commit/c8437322f934aff8ad331a98966e4d948a7ac094). If you'd like to re-create the ThemeFisher map, I'd recommend requesting API keys from Google and inserting them into the previous versions of this template.

I hope this fixes your issue! Please respond with any questions you have.
