### ISSUE TITLE
Do you know how to add social media sharing to the posts?

### ISSUE THREAD

**Issue by piperod** [luminousrubyist/airspace-jekyll#3]

**Comment by luminousrubyist** [comment]
Sorry, i closed this issue accidentally. To add social media sharing to posts you'll need to edit the _layouts/post.html file to add social media sharing buttons or options. To figure out how to embed these, you should visit the social network's website, for instance https://publish.twitter.com, and add the permalink of the current post. I hope this helps! Please let me know if you have any further questions.
